name: "JAVA CI"
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    services:
       postgres:
         image: postgres
         ports:
         - 5432:5432
         env:
           POSTGRES_PASSWORD: postgres
         options: >-
           --health-cmd pg_isready
           --health-interval 10s
           --health-timeout 5s
           --health-retries 5
    steps:
      - name: "🗑 Free disk space"
        run: |
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
          sudo apt-get clean
          df -h
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '18'
          distribution: 'temurin'
      - name: Install maven plugins
        run: mvn install -DskipTests
      - name: Verify prettier
        run: mvn prettier:check -f pom.xml
      - name: Install micronaut
        run: |
          curl -s https://get.sdkman.io | bash
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          sdk install micronaut
      - name: Run the Maven verify phase
        run: mvn --batch-mode --update-snapshots verify
      - name: Run the tests
        run: mvn test